[project]
name = 'Tokenized-Hospitality-Local-Experience-Platforms'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.booking-coordination]
path = 'contracts/booking-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.cultural-authenticity]
path = 'contracts/cultural-authenticity.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
